# Generated by Django 6.0.5 on 2026-05-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp number with country code', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Yoruba', 'Yoruba'), ('Hausa', 'Hausa')], default='English', max_length=10)),
                ('flock_size', models.IntegerField(default=0, help_text='Number of birds in the poultry form')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('sender_type', models.CharField(choices=[('Farmer', 'Farmer'), ('AI', 'AI'), ('Vet', 'Vet')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservations', to='agricore.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_summary', models.TextField()),
                ('ai_preliminary_diagnosis', models.TextField(blank=True, null=True)),
                ('severity_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('In Progress', 'Vet Responding'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('assigned_vet_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricore.farmer')),
            ],
        ),
    ]
