from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from django.http import HttpResponse
from .models import Farmer, Conversation, HealthCase 
import requests 
import os
import time
from dotenv import load_dotenv

load_dotenv(override=True)



def get_ai_response(farmer, message_text):
    """
    Calls Agricare AI API to get the poultry advisory response.
    
    """
    
    raw_key = os.environ.get("AI_API_KEY", "")
    api_key = raw_key.strip().replace('\r', '').replace('\n', '')

    if not api_key:
        print("SECURITY ERROR: No API KEY found! Check your .env file for AI_API_KEY.")
        return "I'm currently experiencing a high volume of queries. Please try again in a moment.", False

    masked_key = f"{api_key[:4]}...{api_key[-4:]}" if len(api_key) > 8 else "INVALID_KEY"
    print(f"SECURE LOG: API Key successfully verified and loaded (Active Key: {masked_key})")

    url = "https://mirah003-agricare-ai-api.hf.space/generateContent"

    headers = {
        "X-API-Key": api_key,
        "Content-Type": "application/json"
    }

    payload = {
        "query": message_text
    }


    # Exponential Backoff Implementation 
    for delay in [1, 2, 4]:
        try: 
            print(f"SECURE LOG: Sending request to Agricare AI: '{message_text[:30]}...'" )
            response = requests.post(url, json=payload, headers=headers, timeout=15)
            print(f"DEBUG: Agricare AI server status code = {response.status_code}")
            if response.status_code == 200:
                result = response.json()
                ai_text = result.get("answer", "No response generated by the model.")

                # HITL / Check High risk case 
                is_high_risk = (
                    "[URGENT]" in ai_text
                    or "Newcastle" in ai_text.lower()
                    or "coccidiosis" in ai_text.lower()
                    or "gumboro" in ai_text.lower()
                )
                print(f"SECURE LOG: Agricare AI Diagnostic query response processed successfully. Risk Level = {is_high_risk}")
                return ai_text, is_high_risk
            # rate limit reached / time out 
            elif response.status_code == 403:
                print("SECURITY ERROR: 403 Forbidden. Check your AI_API_KEY inside your .env file.")
            elif response.status_code == 422:
                print(f"ERROR: 422 Unprocessable Entity. Payload error: {response.text}")

            else:
                print(f"ERROR: Agricare AI API returned unhandled status {response.status_code}")
                print(f"DEBUG RESPONSE: {response.text}")
                break

        except requests.exceptions.RequestException as e:
            print(f"RETRYING: Network or connection error: {str(e)}")
            time.sleep(delay)
            continue

        
    return "Our AI assistant is currently busy. A vet will respond shortly.", False

class WhatsAppWebhookView(APIView):
    """
    FR-01: WhatsApp Conversational Advisory Interface.
    Handles incoming messages from Twilio Sandbox
    """
    def post(self, request):
        # print("DEBUG DATA: ", request.data)
        # Parse incoming data from twilio format 
        from_number = request.data.get('From', '').replace('whatsapp:', '')
        incoming_msg = request.data.get('Body', '')
        profile_name = request.data.get('ProfileName', '')

        if not from_number or not incoming_msg:
            return Response({"error": "Missing message or sender"}, status=status.HTTP_400_BAD_REQUEST)
        
        print(f"SECURE LOG: Webhook Received from phone: {from_number} (Sender Profile Name: '{profile_name}')")  

        # get / create farmer (FR-11: Implicit onboarding) 
        farmer, created = Farmer.objects.get_or_create(phone_number=from_number)

        if created or not farmer.name:
            if profile_name:
                farmer.name = profile_name
                farmer.is_onboarded = True
                farmer.save()
                print(f" PROFILE UPDATE: Implicitly onboarded '{profile_name}' based on WhatsApp profile data!")  
        # log Farmer's Message (FR-01: History Retention)
        Conversation.objects.create(
            farmer=farmer,
            message_text=incoming_msg,
            sender_type='Farmer'
        )

        # Get Diagnostic advice from Agricare AI
        ai_text, is_high_risk = get_ai_response(farmer, incoming_msg)

        # FR-07 (Automatic High risk Triage & HITL Escalation)
        if is_high_risk:
            HealthCase.objects.get_or_create(
                farmer=farmer,
                status='Pending',
                defaults={
                    'symptoms_summary': incoming_msg,
                    'ai_preliminary_diagnosis': ai_text,
                    'severity_score': 0.95
                }
            )

        # log ai response 
        Conversation.objects.create(
            farmer=farmer,
            message_text=ai_text,
            sender_type='AI'
        )

        # Deliver response back to farmer via TwiML (the XML format Twilio uses to reply to messages)
        response_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
        <Response>
            <Message>{ai_text}</Message>
        </Response>"""

        return HttpResponse(response_xml, content_type="application/xml")
    
    def get(self, request):
        """
        Required for Meta WhatsApp Business API Webhook Verification.
        """
        verify_token = os.environ.get("WHATSAPP_VERIFY_TOKEN", "agricare_secret_token")
        mode = request.GET.get('hub.mode')
        token = request.GET.get('hub.verify_token')
        challenge = request.GET.get('hub.challenge')

        if mode == 'subscribe' and token == verify_token:
            return HttpResponse(challenge)
        return HttpResponse("Verification Token Mismatch", status=403)
